import type { SharedSetDetail } from '../../types/marketplace';

const now = new Date().toISOString();
const weekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();
const monthAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_SHARED_SETS: SharedSetDetail[] = [
  // ── Anna RN ─────────────────────────────────────────────────────────────────
  {
    id: 'set_fundamentals_safety_001',
    slug: 'fundamentals-safety-priority-pack',
    title: 'Fundamentals Safety Priority Pack',
    description: 'High-yield fundamentals questions focused on priority actions, delegation, and bedside safety checks.',
    tags: ['fundamentals', 'priority', 'delegation', 'safety'],
    subject: 'Fundamentals of Nursing',
    visibility: 'public',
    version: 3,
    downloads: 1824,
    ratingAverage: 4.8,
    ratingCount: 233,
    questionCount: 6,
    createdAt: monthAgo,
    updatedAt: monthAgo,
    author: {
      id: 'author_anna_rn',
      displayName: 'Anna, RN',
      avatarUrl: 'avataaars:AnnaRN|skinColor[]=edb98a&top[]=longButNotTooLong&hairColor[]=a55728&facialHairProbability=0&clothing[]=shirtVNeck&clothingColor[]=65c9ff&mouth[]=smile&eyebrows[]=defaultNatural',
      country: 'US',
      bio: 'ICU nurse with 8 years experience. Passionate about NCLEX prep and evidence-based practice.',
      studyField: 'Critical Care Nursing',
    },
    questions: [
      {
        id: 'q_fund_1', remoteQuestionId: 'fund_1',
        content: 'Which patient should the nurse assess first after shift handoff?',
        rationale: 'Prioritize airway, breathing, and circulation risks. The patient with breathing compromise is first.',
        options: ['Post-op pain 7/10', 'O2 sat 88% on room air', 'Requesting discharge papers', 'Needs dressing change'],
        answers: ['O2 sat 88% on room air'], tags: ['priority', 'abc'], orderIndex: 1, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_fund_2', remoteQuestionId: 'fund_2',
        content: 'Which task is appropriate to delegate to UAP for a stable client?',
        rationale: 'UAP can perform routine, non-assessment tasks for stable clients.',
        options: ['Initial admission assessment', 'Teach insulin injection', 'Obtain routine vital signs', 'Evaluate pain intervention'],
        answers: ['Obtain routine vital signs'], tags: ['delegation'], orderIndex: 2, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_fund_3', remoteQuestionId: 'fund_3',
        content: 'Which action best reduces fall risk for an older adult at night?',
        rationale: 'Environmental safety and access to assistance reduce fall incidents.',
        options: ['Raise all four bed rails', 'Keep bed low and call light within reach', 'Limit toileting overnight', 'Use wrist restraints'],
        answers: ['Keep bed low and call light within reach'], tags: ['safety', 'falls'], orderIndex: 3, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_fund_4', remoteQuestionId: 'fund_4',
        content: 'Before medication administration, which identifier check is required?',
        rationale: 'Use at least two unique patient identifiers.',
        options: ['Room number and diagnosis', 'Name and date of birth', 'Bed number and physician name', 'Last name only'],
        answers: ['Name and date of birth'], tags: ['med safety'], orderIndex: 4, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_fund_5', remoteQuestionId: 'fund_5',
        content: 'A sterile field is considered contaminated when:',
        rationale: 'Any break in sterile technique contaminates the field.',
        options: ['Field is above waist level', 'Nurse turns away from field', 'Outer 1 inch touched with sterile glove', 'Dry package placed near field'],
        answers: ['Nurse turns away from field'], tags: ['infection control'], orderIndex: 5, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_fund_6', remoteQuestionId: 'fund_6',
        content: 'Which statement reflects therapeutic communication?',
        rationale: 'Open-ended, patient-centered prompts support expression.',
        options: ['Why did you do that?', 'You should not feel that way.', 'Tell me more about what worries you.', 'Everything will be fine.'],
        answers: ['Tell me more about what worries you.'], tags: ['communication'], orderIndex: 6, createdAt: now, updatedAt: now,
      },
    ],
  },

  {
    id: 'set_health_assessment_001',
    slug: 'health-assessment-head-to-toe',
    title: 'Health Assessment: Head-to-Toe Guide',
    description: 'Comprehensive head-to-toe assessment techniques, findings interpretation, and documentation essentials.',
    tags: ['assessment', 'physical exam', 'documentation', 'nclex'],
    subject: 'Health Assessment',
    visibility: 'public',
    version: 2,
    downloads: 1102,
    ratingAverage: 4.9,
    ratingCount: 148,
    questionCount: 4,
    createdAt: weekAgo,
    updatedAt: weekAgo,
    author: {
      id: 'author_anna_rn',
      displayName: 'Anna, RN',
      avatarUrl: 'avataaars:AnnaRN|skinColor[]=edb98a&top[]=longButNotTooLong&hairColor[]=a55728&facialHairProbability=0&clothing[]=shirtVNeck&clothingColor[]=65c9ff&mouth[]=smile&eyebrows[]=defaultNatural',
      country: 'US',
      bio: 'ICU nurse with 8 years experience. Passionate about NCLEX prep and evidence-based practice.',
      studyField: 'Critical Care Nursing',
    },
    questions: [
      {
        id: 'q_ha_1', remoteQuestionId: 'ha_1',
        content: 'When auscultating breath sounds, crackles (rales) are most often associated with:',
        rationale: 'Crackles result from fluid in alveoli, characteristic of pneumonia or pulmonary edema.',
        options: ['Asthma exacerbation', 'Pulmonary edema or pneumonia', 'Pleural friction rub', 'Normal breathing'],
        answers: ['Pulmonary edema or pneumonia'], tags: ['respiratory', 'auscultation'], orderIndex: 1, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_ha_2', remoteQuestionId: 'ha_2',
        content: 'A capillary refill time greater than 3 seconds indicates:',
        rationale: 'Prolonged capillary refill suggests reduced peripheral perfusion.',
        options: ['Normal circulation', 'Reduced peripheral perfusion', 'Infection', 'Dehydration only'],
        answers: ['Reduced peripheral perfusion'], tags: ['circulation', 'perfusion'], orderIndex: 2, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_ha_3', remoteQuestionId: 'ha_3',
        content: 'The best position to assess JVD (jugular venous distension) is:',
        rationale: 'Semi-Fowler\'s at 30-45 degrees allows optimal visualization of jugular veins.',
        options: ['Supine flat', 'Semi-Fowler\'s 30-45°', 'Sitting upright 90°', 'Prone'],
        answers: ['Semi-Fowler\'s 30-45°'], tags: ['cardiovascular', 'JVD'], orderIndex: 3, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_ha_4', remoteQuestionId: 'ha_4',
        content: 'Which finding requires immediate reporting to the physician?',
        rationale: 'Sudden change in level of consciousness is a critical neurological warning sign.',
        options: ['Blood pressure 128/82 mmHg', 'Temperature 37.2°C', 'Sudden change in LOC', 'Pulse 78 bpm regular'],
        answers: ['Sudden change in LOC'], tags: ['neuro', 'priority'], orderIndex: 4, createdAt: now, updatedAt: now,
      },
    ],
  },

  // ── Malik NP ────────────────────────────────────────────────────────────────
  {
    id: 'set_pharm_cardio_001',
    slug: 'pharm-cardio-essentials',
    title: 'Pharmacology Cardio Essentials',
    description: 'Core cardiovascular medication questions with mechanisms, side effects, and nursing actions.',
    tags: ['pharmacology', 'cardiology', 'dosage', 'nclex'],
    subject: 'Pharmacology',
    visibility: 'public',
    version: 2,
    downloads: 1260,
    ratingAverage: 4.7,
    ratingCount: 175,
    questionCount: 4,
    createdAt: monthAgo,
    updatedAt: monthAgo,
    author: {
      id: 'author_malik_np',
      displayName: 'Malik, NP',
      avatarUrl: 'avataaars:MalikNP|skinColor[]=614335&top[]=shortFlat&hairColor[]=2c1b18&facialHair[]=beardLight&facialHairProbability=100&clothing[]=blazerAndShirt&clothingColor[]=262e33&mouth[]=smile&eyebrows[]=defaultNatural',
      country: 'NG',
      bio: 'Nurse Practitioner specializing in cardiology and pharmacology. 5 years in clinical practice, 3 years teaching.',
      studyField: 'Advanced Practice Nursing',
    },
    questions: [
      {
        id: 'q_pharm_1', remoteQuestionId: 'pharm_1',
        content: 'Which lab value should be monitored for a patient on ACE inhibitors?',
        rationale: 'ACE inhibitors can increase potassium and affect renal function.',
        options: ['Serum calcium', 'Serum potassium', 'Hemoglobin A1c', 'Amylase'],
        answers: ['Serum potassium'], tags: ['ace inhibitors'], orderIndex: 1, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_pharm_2', remoteQuestionId: 'pharm_2',
        content: 'Common adverse effect of beta blockers includes:',
        rationale: 'Beta blockers lower heart rate and may cause bradycardia/fatigue.',
        options: ['Tachycardia', 'Bradycardia', 'Hyperreflexia', 'Diuresis'],
        answers: ['Bradycardia'], tags: ['beta blockers'], orderIndex: 2, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_pharm_3', remoteQuestionId: 'pharm_3',
        content: 'Before giving digoxin, the nurse should first assess:',
        rationale: 'Hold and clarify if apical pulse is below threshold per order/policy.',
        options: ['Respiratory rate', 'Apical pulse', 'Blood glucose', 'Pain score'],
        answers: ['Apical pulse'], tags: ['digoxin'], orderIndex: 3, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_pharm_4', remoteQuestionId: 'pharm_4',
        content: 'Which instruction is most important for a client taking warfarin?',
        rationale: 'Warfarin requires INR monitoring and bleeding precautions.',
        options: ['Avoid all green vegetables', 'Use aspirin for headaches', 'Keep INR monitoring appointments', 'Stop medication before dental cleanings'],
        answers: ['Keep INR monitoring appointments'], tags: ['warfarin'], orderIndex: 4, createdAt: now, updatedAt: now,
      },
    ],
  },

  {
    id: 'set_pharm_antibiotics_001',
    slug: 'nclex-pharmacology-antibiotics',
    title: 'NCLEX Pharmacology: Antibiotics',
    description: 'Must-know antibiotic classes, mechanisms, nursing considerations, and client teaching points.',
    tags: ['pharmacology', 'antibiotics', 'infection', 'nclex'],
    subject: 'Pharmacology',
    visibility: 'public',
    version: 1,
    downloads: 843,
    ratingAverage: 4.6,
    ratingCount: 97,
    questionCount: 4,
    createdAt: weekAgo,
    updatedAt: weekAgo,
    author: {
      id: 'author_malik_np',
      displayName: 'Malik, NP',
      avatarUrl: 'avataaars:MalikNP|skinColor[]=614335&top[]=shortFlat&hairColor[]=2c1b18&facialHair[]=beardLight&facialHairProbability=100&clothing[]=blazerAndShirt&clothingColor[]=262e33&mouth[]=smile&eyebrows[]=defaultNatural',
      country: 'NG',
      bio: 'Nurse Practitioner specializing in cardiology and pharmacology. 5 years in clinical practice, 3 years teaching.',
      studyField: 'Advanced Practice Nursing',
    },
    questions: [
      {
        id: 'q_ab_1', remoteQuestionId: 'ab_1',
        content: 'A client on penicillin develops hives and wheezing. Priority action?',
        rationale: 'Stop the medication immediately — signs of anaphylaxis.',
        options: ['Slow the infusion rate', 'Administer diphenhydramine first', 'Stop medication and notify provider', 'Document and continue'],
        answers: ['Stop medication and notify provider'], tags: ['allergy', 'anaphylaxis'], orderIndex: 1, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_ab_2', remoteQuestionId: 'ab_2',
        content: 'Which antibiotic class is contraindicated in children under 8 due to teeth staining?',
        rationale: 'Tetracyclines bind to calcium in developing teeth and bones.',
        options: ['Penicillins', 'Cephalosporins', 'Tetracyclines', 'Macrolides'],
        answers: ['Tetracyclines'], tags: ['pediatrics', 'tetracyclines'], orderIndex: 2, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_ab_3', remoteQuestionId: 'ab_3',
        content: 'Vancomycin toxicity monitoring requires checking:',
        rationale: 'Vancomycin is nephrotoxic and ototoxic — monitor renal function and trough levels.',
        options: ['Liver enzymes only', 'Serum creatinine and trough levels', 'CBC only', 'Serum glucose'],
        answers: ['Serum creatinine and trough levels'], tags: ['vancomycin', 'monitoring'], orderIndex: 3, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_ab_4', remoteQuestionId: 'ab_4',
        content: 'A client taking metronidazole should be instructed to avoid:',
        rationale: 'Metronidazole causes a disulfiram-like reaction with alcohol.',
        options: ['Dairy products', 'Alcohol', 'Sunlight', 'Grapefruit juice'],
        answers: ['Alcohol'], tags: ['metronidazole', 'teaching'], orderIndex: 4, createdAt: now, updatedAt: now,
      },
    ],
  },

  // ── Joan Peds RN ─────────────────────────────────────────────────────────────
  {
    id: 'set_peds_growth_001',
    slug: 'pediatrics-growth-development-check',
    title: 'Pediatrics Growth & Development Check',
    description: 'Developmental milestone and family-centered care questions for pediatric prep.',
    tags: ['pediatrics', 'milestones', 'family education'],
    subject: 'Pediatric Nursing',
    visibility: 'public',
    version: 1,
    downloads: 904,
    ratingAverage: 4.6,
    ratingCount: 114,
    questionCount: 3,
    createdAt: monthAgo,
    updatedAt: monthAgo,
    author: {
      id: 'author_joan_peds',
      displayName: 'Joan Peds RN',
      avatarUrl: 'avataaars:JoanPeds|skinColor[]=edb98a&top[]=bob&hairColor[]=d6b370&facialHairProbability=0&clothing[]=collarAndSweater&clothingColor[]=b1e2ff&mouth[]=smile&eyebrows[]=defaultNatural',
      country: 'CA',
      bio: 'Pediatric RN at SickKids. Focused on family-centered care, developmental milestones, and pediatric pharmacology.',
      studyField: 'Pediatric Nursing',
    },
    questions: [
      {
        id: 'q_peds_1', remoteQuestionId: 'peds_1',
        content: 'At what age does a child typically begin to walk independently?',
        rationale: 'Independent walking commonly appears around 12 months.',
        options: ['6 months', '9 months', '12 months', '18 months'],
        answers: ['12 months'], tags: ['milestones'], orderIndex: 1, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_peds_2', remoteQuestionId: 'peds_2',
        content: 'Which play activity is most appropriate for a toddler?',
        rationale: 'Toddlers benefit from parallel play and simple imitation activities.',
        options: ['Competitive board games', 'Parallel block play', 'Complex puzzle strategy', 'Formal team sports'],
        answers: ['Parallel block play'], tags: ['development'], orderIndex: 2, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_peds_3', remoteQuestionId: 'peds_3',
        content: 'Best approach when teaching inhaler use to parents of a child with asthma?',
        rationale: 'Demonstration plus return demonstration confirms understanding.',
        options: ['Provide brochure only', 'Ask parent to watch online video later', 'Demonstrate and have parent return-demonstrate', 'Delay until discharge day'],
        answers: ['Demonstrate and have parent return-demonstrate'], tags: ['education', 'asthma'], orderIndex: 3, createdAt: now, updatedAt: now,
      },
    ],
  },

  // ── Sarah PMHNP ──────────────────────────────────────────────────────────────
  {
    id: 'set_mental_health_crisis_001',
    slug: 'mental-health-crisis-intervention',
    title: 'Mental Health Crisis Intervention',
    description: 'De-escalation techniques, suicide risk assessment, and safe management of acute psychiatric crises.',
    tags: ['mental health', 'crisis', 'de-escalation', 'suicide risk'],
    subject: 'Mental Health/Psychiatric Nursing',
    visibility: 'public',
    version: 2,
    downloads: 756,
    ratingAverage: 4.5,
    ratingCount: 88,
    questionCount: 4,
    createdAt: weekAgo,
    updatedAt: weekAgo,
    author: {
      id: 'author_sarah_psych',
      displayName: 'Sarah, PMHNP',
      avatarUrl: 'avataaars:SarahPsych|skinColor[]=edb98a&top[]=curly&hairColor[]=724133&facialHairProbability=0&clothing[]=blazerAndSweater&clothingColor[]=929598&mouth[]=smile&eyebrows[]=defaultNatural',
      country: 'GB',
      bio: 'Psychiatric Mental Health Nurse Practitioner. Specializing in mood disorders and crisis stabilization.',
      studyField: 'Psychiatric Nursing',
    },
    questions: [
      {
        id: 'q_mh_1', remoteQuestionId: 'mh_1',
        content: 'When assessing suicide risk, which question is most direct and appropriate?',
        rationale: 'Directly asking about suicidal ideation does not increase risk and clarifies intent.',
        options: ['Are you feeling sad?', 'Are you thinking about hurting yourself?', 'Do you have problems at home?', 'Have you been sleeping well?'],
        answers: ['Are you thinking about hurting yourself?'], tags: ['suicide', 'assessment'], orderIndex: 1, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_mh_2', remoteQuestionId: 'mh_2',
        content: 'Priority nursing intervention for a client who is agitated and escalating:',
        rationale: 'De-escalation using a calm, non-threatening approach is the first intervention.',
        options: ['Apply restraints immediately', 'Use calm, low voice and de-escalation techniques', 'Administer PRN sedative first', 'Leave the room to avoid confrontation'],
        answers: ['Use calm, low voice and de-escalation techniques'], tags: ['de-escalation'], orderIndex: 2, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_mh_3', remoteQuestionId: 'mh_3',
        content: 'A client on lithium reports nausea, tremor, and blurred vision. Nurse should:',
        rationale: 'These are signs of lithium toxicity; hold the dose and check serum lithium level.',
        options: ['Give the next dose with food', 'Hold dose and check serum lithium level', 'Reassure and continue treatment', 'Increase fluid intake only'],
        answers: ['Hold dose and check serum lithium level'], tags: ['lithium', 'toxicity'], orderIndex: 3, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_mh_4', remoteQuestionId: 'mh_4',
        content: 'Which therapeutic approach uses identifying distorted thought patterns?',
        rationale: 'CBT focuses on identifying and restructuring negative cognitive patterns.',
        options: ['Psychoanalysis', 'Cognitive Behavioral Therapy (CBT)', 'Gestalt therapy', 'Dialectical Exposure Therapy'],
        answers: ['Cognitive Behavioral Therapy (CBT)'], tags: ['CBT', 'therapy'], orderIndex: 4, createdAt: now, updatedAt: now,
      },
    ],
  },

  // ── Carlos RN ────────────────────────────────────────────────────────────────
  {
    id: 'set_medsurg_postop_001',
    slug: 'post-op-care-essentials',
    title: 'Post-Op Care Essentials',
    description: 'Key post-operative assessment priorities, complication prevention, and patient education for NCLEX.',
    tags: ['med-surg', 'post-op', 'surgery', 'complications'],
    subject: 'Medical-Surgical Nursing',
    visibility: 'public',
    version: 1,
    downloads: 891,
    ratingAverage: 4.6,
    ratingCount: 103,
    questionCount: 4,
    createdAt: now,
    updatedAt: now,
    author: {
      id: 'author_carlos_rn',
      displayName: 'Carlos, RN',
      avatarUrl: 'avataaars:CarlosRN|skinColor[]=d08b5b&top[]=shortCurly&hairColor[]=2c1b18&facialHair[]=moustacheFancy&facialHairProbability=100&clothing[]=shirtCrewNeck&clothingColor[]=5199e4&mouth[]=smile&eyebrows[]=defaultNatural',
      country: 'PH',
      bio: 'Med-Surg RN with 6 years of experience in surgical floors and step-down units. NCLEX tutor.',
      studyField: 'Medical-Surgical Nursing',
    },
    questions: [
      {
        id: 'q_po_1', remoteQuestionId: 'po_1',
        content: 'First nursing priority when a post-op patient returns from the PACU:',
        rationale: 'Airway is always the first priority — assess for patency and adequacy of breathing.',
        options: ['Check surgical site for bleeding', 'Assess airway and respiratory status', 'Review medication orders', 'Obtain vital signs baseline'],
        answers: ['Assess airway and respiratory status'], tags: ['priority', 'airway', 'PACU'], orderIndex: 1, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_po_2', remoteQuestionId: 'po_2',
        content: 'To prevent post-operative atelectasis, the nurse should encourage:',
        rationale: 'Deep breathing exercises and incentive spirometry expand alveoli and prevent collapse.',
        options: ['Bed rest for 24 hours', 'Incentive spirometry and deep breathing', 'Restrict fluids to minimize secretions', 'Prone positioning only'],
        answers: ['Incentive spirometry and deep breathing'], tags: ['respiratory', 'atelectasis'], orderIndex: 2, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_po_3', remoteQuestionId: 'po_3',
        content: 'Signs of wound dehiscence include:',
        rationale: 'Dehiscence is separation of wound edges; patient may feel a "popping" sensation.',
        options: ['Redness and warmth only', 'Separation of wound edges with possible evisceration', 'Fever and increased WBC', 'Localized swelling'],
        answers: ['Separation of wound edges with possible evisceration'], tags: ['wound', 'complications'], orderIndex: 3, createdAt: now, updatedAt: now,
      },
      {
        id: 'q_po_4', remoteQuestionId: 'po_4',
        content: 'Which intervention best prevents DVT in a post-surgical patient?',
        rationale: 'Early ambulation and sequential compression devices reduce venous stasis.',
        options: ['Keep legs elevated at rest only', 'Early ambulation and sequential compression devices', 'Bed rest for 48 hours', 'Aspirin 81mg only'],
        answers: ['Early ambulation and sequential compression devices'], tags: ['DVT', 'prevention'], orderIndex: 4, createdAt: now, updatedAt: now,
      },
    ],
  },
];
