import type { SharedSetDetail } from '../../types/marketplace';

const now = new Date().toISOString();

export const MOCK_SHARED_SETS: SharedSetDetail[] = [
  {
    id: 'set_fundamentals_safety_001',
    slug: 'fundamentals-safety-priority-pack',
    title: 'Fundamentals Safety Priority Pack',
    description:
      'High-yield fundamentals questions focused on priority actions, delegation, and bedside safety checks.',
    tags: ['fundamentals', 'priority', 'delegation', 'safety'],
    subject: 'Fundamentals of Nursing',
    visibility: 'public',
    version: 3,
    downloads: 1824,
    ratingAverage: 4.8,
    ratingCount: 233,
    questionCount: 6,
    createdAt: now,
    updatedAt: now,
    author: {
      id: 'author_anna_rn',
      displayName: 'Anna, RN',
    },
    questions: [
      {
        id: 'q_fund_1',
        remoteQuestionId: 'fund_1',
        content: 'Which patient should the nurse assess first after shift handoff?',
        rationale:
          'Prioritize airway, breathing, and circulation risks. The patient with breathing compromise is first.',
        options: ['Post-op pain 7/10', 'O2 sat 88% on room air', 'Requesting discharge papers', 'Needs dressing change'],
        answers: ['O2 sat 88% on room air'],
        tags: ['priority', 'abc'],
        orderIndex: 1,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'q_fund_2',
        remoteQuestionId: 'fund_2',
        content: 'Which task is appropriate to delegate to UAP for a stable client?',
        rationale: 'UAP can perform routine, non-assessment tasks for stable clients.',
        options: ['Initial admission assessment', 'Teach insulin injection', 'Obtain routine vital signs', 'Evaluate pain intervention'],
        answers: ['Obtain routine vital signs'],
        tags: ['delegation'],
        orderIndex: 2,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'q_fund_3',
        remoteQuestionId: 'fund_3',
        content: 'Which action best reduces fall risk for an older adult at night?',
        rationale: 'Environmental safety and access to assistance reduce fall incidents.',
        options: ['Raise all four bed rails', 'Keep bed low and call light within reach', 'Limit toileting overnight', 'Use wrist restraints'],
        answers: ['Keep bed low and call light within reach'],
        tags: ['safety', 'falls'],
        orderIndex: 3,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'q_fund_4',
        remoteQuestionId: 'fund_4',
        content: 'Before medication administration, which identifier check is required?',
        rationale: 'Use at least two unique patient identifiers.',
        options: ['Room number and diagnosis', 'Name and date of birth', 'Bed number and physician name', 'Last name only'],
        answers: ['Name and date of birth'],
        tags: ['med safety'],
        orderIndex: 4,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'q_fund_5',
        remoteQuestionId: 'fund_5',
        content: 'A sterile field is considered contaminated when:',
        rationale: 'Any break in sterile technique contaminates the field.',
        options: ['Field is above waist level', 'Nurse turns away from field', 'Outer 1 inch touched with sterile glove', 'Dry package placed near field'],
        answers: ['Nurse turns away from field'],
        tags: ['infection control'],
        orderIndex: 5,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'q_fund_6',
        remoteQuestionId: 'fund_6',
        content: 'Which statement reflects therapeutic communication?',
        rationale: 'Open-ended, patient-centered prompts support expression.',
        options: ['Why did you do that?', 'You should not feel that way.', 'Tell me more about what worries you.', 'Everything will be fine.'],
        answers: ['Tell me more about what worries you.'],
        tags: ['communication'],
        orderIndex: 6,
        createdAt: now,
        updatedAt: now,
      },
    ],
  },
  {
    id: 'set_pharm_cardio_001',
    slug: 'pharm-cardio-essentials',
    title: 'Pharmacology Cardio Essentials',
    description: 'Core cardiovascular medication questions with mechanisms, side effects, and nursing actions.',
    tags: ['pharmacology', 'cardiology', 'dosage'],
    subject: 'Pharmacology',
    visibility: 'public',
    version: 2,
    downloads: 1260,
    ratingAverage: 4.7,
    ratingCount: 175,
    questionCount: 4,
    createdAt: now,
    updatedAt: now,
    author: {
      id: 'author_malik_np',
      displayName: 'Malik, NP',
    },
    questions: [
      {
        id: 'q_pharm_1',
        remoteQuestionId: 'pharm_1',
        content: 'Which lab value should be monitored for a patient on ACE inhibitors?',
        rationale: 'ACE inhibitors can increase potassium and affect renal function.',
        options: ['Serum calcium', 'Serum potassium', 'Hemoglobin A1c', 'Amylase'],
        answers: ['Serum potassium'],
        tags: ['ace inhibitors'],
        orderIndex: 1,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'q_pharm_2',
        remoteQuestionId: 'pharm_2',
        content: 'Common adverse effect of beta blockers includes:',
        rationale: 'Beta blockers lower heart rate and may cause bradycardia/fatigue.',
        options: ['Tachycardia', 'Bradycardia', 'Hyperreflexia', 'Diuresis'],
        answers: ['Bradycardia'],
        tags: ['beta blockers'],
        orderIndex: 2,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'q_pharm_3',
        remoteQuestionId: 'pharm_3',
        content: 'Before giving digoxin, the nurse should first assess:',
        rationale: 'Hold and clarify if apical pulse is below threshold per order/policy.',
        options: ['Respiratory rate', 'Apical pulse', 'Blood glucose', 'Pain score'],
        answers: ['Apical pulse'],
        tags: ['digoxin'],
        orderIndex: 3,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'q_pharm_4',
        remoteQuestionId: 'pharm_4',
        content: 'Which instruction is most important for a client taking warfarin?',
        rationale: 'Warfarin requires INR monitoring and bleeding precautions.',
        options: ['Avoid all green vegetables', 'Use aspirin for headaches', 'Keep INR monitoring appointments', 'Stop medication before dental cleanings'],
        answers: ['Keep INR monitoring appointments'],
        tags: ['warfarin'],
        orderIndex: 4,
        createdAt: now,
        updatedAt: now,
      },
    ],
  },
  {
    id: 'set_peds_growth_001',
    slug: 'pediatrics-growth-development-check',
    title: 'Pediatrics Growth & Development Check',
    description: 'Developmental milestone and family-centered care questions for pediatric prep.',
    tags: ['pediatrics', 'milestones', 'family education'],
    subject: 'Pediatric Nursing',
    visibility: 'public',
    version: 1,
    downloads: 904,
    ratingAverage: 4.6,
    ratingCount: 114,
    questionCount: 3,
    createdAt: now,
    updatedAt: now,
    author: {
      id: 'author_joan_peds',
      displayName: 'Joan Peds RN',
    },
    questions: [
      {
        id: 'q_peds_1',
        remoteQuestionId: 'peds_1',
        content: 'At what age does a child typically begin to walk independently?',
        rationale: 'Independent walking commonly appears around 12 months.',
        options: ['6 months', '9 months', '12 months', '18 months'],
        answers: ['12 months'],
        tags: ['milestones'],
        orderIndex: 1,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'q_peds_2',
        remoteQuestionId: 'peds_2',
        content: 'Which play activity is most appropriate for a toddler?',
        rationale: 'Toddlers benefit from parallel play and simple imitation activities.',
        options: ['Competitive board games', 'Parallel block play', 'Complex puzzle strategy', 'Formal team sports'],
        answers: ['Parallel block play'],
        tags: ['development'],
        orderIndex: 2,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'q_peds_3',
        remoteQuestionId: 'peds_3',
        content: 'Best approach when teaching inhaler use to parents of a child with asthma?',
        rationale: 'Demonstration plus return demonstration confirms understanding.',
        options: ['Provide brochure only', 'Ask parent to watch online video later', 'Demonstrate and have parent return-demonstrate', 'Delay until discharge day'],
        answers: ['Demonstrate and have parent return-demonstrate'],
        tags: ['education', 'asthma'],
        orderIndex: 3,
        createdAt: now,
        updatedAt: now,
      },
    ],
  },
];
